# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a7025a072d84ee69326fde44b27cd10e3a7a296700d1f9ce6dca69a9f7f6f8a86c872d426a48085d4cf232307bfa338654de06bff1f43db7ec6a290da06cfec

test:
  secret_key_base: 257f70146e4bc3ef9232f2b3773abea7a89b8e43a056db9eb4351420c863c9f44c59b0ad40d14ed8e6f19f491c934ba473ac07ac846a8a0999cd0c726fc9fc86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
